global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'railway-monitoring'

scrape_configs:
  # Prometheus самомониторинг
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  # Directus с встроенными метриками (включая PostgreSQL и Redis)
  - job_name: 'directus'
    scrape_interval: 60s
    static_configs:
      - targets: ['empowering-love.railway.internal:8080']
    metrics_path: '/metrics'
    headers:
      Authorization: 'Metrics BMHx7HZo8GA1jlEP1oT8y6-hW7IFBrpz'
