global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'railway-monitoring'

scrape_configs:
  # Prometheus самомониторинг
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL метрики
  - job_name: 'postgres'
    scrape_interval: 60s
    static_configs:
      - targets: ['postgres-metrics-collector.railway.internal:9187']
    metrics_path: '/metrics'
    scheme: 'http'

  # Redis метрики через redis_exporter
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis-metrics-collector.railway.internal:9121']
    metrics_path: '/metrics'
    scheme: 'http' 
    scrape_timeout: 60s


  # Directus с встроенными метриками (включая PostgreSQL и Redis)
  - job_name: 'directus'
    scrape_interval: 60s
    static_configs:
      - targets: ['empowering-love.railway.internal:8080']
    metrics_path: '/metrics'
    authorization:
      credentials: 'BMHx7HZo8GA1jlEP1oT8y6-hW7IFBrpz'

  # Astro.js сайт с кастомными метриками
  - job_name: 'astro'
    scrape_interval: 60s
    static_configs:
      - targets: ['daloras.com']
    metrics_path: '/api/metrics'
    scheme: 'https'
    scrape_timeout: 10s
    params:
      method: ['POST']